apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deploy
spec:
    selector:
        matchLabels:
            app: nginx-svc
    replicas: 1
    template:
        metadata:
            labels:
                app: nginx-svc
        spec:
            containers:
            - name: nginx
              image: nginx:matrus
              imagePullPolicy: Never
              ports:
              - containerPort: 80
              - containerPort: 443
              - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
    name: nginx-svc
    labels:
        app: nginx-svc
spec:
    selector:
        app: nginx-svc
    type: LoadBalancer
    ports:
        - port: 80
          name: http
          protocol: TCP
          targetPort: 80
        - port: 443
          name: https
          protocol: TCP
          targetPort: 443
        - port: 22
          name: ssh
          protocol: TCP
          targetPort: 22
