apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    labels:
        app: nginx-svc
spec:
    selector:
        app: nginx-svc
    type: LoadBalancer
    ports:
        - port: 80
          name: http
          protocol: TCP
          targetPort: 80
        - port: 443
          name: https
          protocol: TCP
          targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
spec:
    selector:
        matchLabels:
            app: nginx-svc
    replicas: 1
    template:
        metadata:
            labels:
                app: nginx-svc
        spec:
            containers:
            - name: nginx
              image: ng-test:1
              imagePullPolicy: Never
              ports:
              - containerPort: 80
              - containerPort: 443
